openapi: 3.0.0
info:
  contact:
    email: xiachengjia@speakin.mobi
  description: api document
  license:
    name: Mit
    url: https://opensource.org/licenses/MIT
  title: 声纹云api
  version: /cloudapi/v1beta
servers:
- description: dev
  url: https://vpc.speakin.mobi
tags:
- name: storage
- name: voiceprint
paths:
  /cloudapi/v1beta/voiceprint/query:
    post:
      description: 声纹查询
      operationId: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintQueryRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintQueryResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/register:
    post:
      description: 声纹注册
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintRegisterRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintRegisterResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verify:
    post:
      description: 声纹验证
      operationId: verify
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verify1ton:
    post:
      description: 声纹验证
      operationId: verify1ton
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Voiceprint1tonVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprint1tonVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verifytopn:
    post:
      description: 声纹验证
      operationId: verifytopn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprinttopnVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprinttopnVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/delete:
    post:
      description: 声纹查询
      operationId: delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintDeleteRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintDeleteResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/threshold:
    post:
      description: 查询阈值
      operationId: threshold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintThresholdRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintThresholdResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/vadcheck:
    post:
      description: VAD检测
      operationId: vadcheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVadcheckRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVadcheckResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/ctcdasr:
    post:
      description: 数字asr
      operationId: ctcdasr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintCtcdasrRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintCtcdasrResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verify_multi:
    post:
      description: 声纹验证1对多
      operationId: verify_multi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVerifyMultiRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVerifyMultiResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/storage/upload:
    post:
      description: 上传文件
      operationId: upload
      parameters:
      - explode: true
        in: query
        name: bucket
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: type
        required: true
        schema:
          example: wav
          type: string
        style: form
      - explode: true
        in: query
        name: durationMS
        required: false
        schema:
          example: 0
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: timestamp
        required: true
        schema:
          example: 123
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body'
        description: 上传文件
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallUploadResponse'
          description: 响应参数
      tags:
      - storage
  /cloudapi/v1beta/storage/download:
    get:
      description: 下载文件
      operationId: download
      parameters:
      - explode: true
        in: query
        name: bucket
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: key
        required: true
        schema:
          example: "123"
          type: string
        style: form
      responses:
        200:
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: 二进制文件
      tags:
      - storage
components:
  schemas:
    CallUploadResponse:
      example:
        errorDesc: errorDesc
        data:
          key: "123"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/UploadResponse'
      type: object
      xml:
        name: CallUploadResponse
    RespVoiceprint1tonVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 0.5
          unionID: "123"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/Voiceprint1tonVerifyResponse'
      type: object
      xml:
        name: RespVoiceprint1tonVerifyResponse
    RespVoiceprintCtcdasrResponse:
      example:
        errorDesc: errorDesc
        data:
          asrString: "123456"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintCtcdasrResponse'
      type: object
      xml:
        name: RespVoiceprintCtcdasrResponse
    RespVoiceprintDeleteResponse:
      example:
        errorDesc: errorDesc
        data: ""
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          xml:
            name: VoiceprintDeleteResponse
      type: object
      xml:
        name: RespVoiceprintDeleteResponse
    RespVoiceprintQueryResponse:
      example:
        errorDesc: errorDesc
        data:
          isRegister: true
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintQueryResponse'
      type: object
      xml:
        name: RespVoiceprintQueryResponse
    RespVoiceprintRegisterResponse:
      example:
        errorDesc: errorDesc
        data: ""
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          xml:
            name: VoiceprintRegisterResponse
      type: object
      xml:
        name: RespVoiceprintRegisterResponse
    RespVoiceprintThresholdResponse:
      example:
        errorDesc: errorDesc
        data:
          threshold: 0.38
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintThresholdResponse'
      type: object
      xml:
        name: RespVoiceprintThresholdResponse
    RespVoiceprintVadcheckResponse:
      example:
        errorDesc: errorDesc
        data:
          code: code
          status: status
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVadcheckResponse'
      type: object
      xml:
        name: RespVoiceprintVadcheckResponse
    RespVoiceprintVerifyMultiResponse:
      example:
        errorDesc: errorDesc
        data:
          report:
          - unionID: use_one
            score: 99
          - unionID: use_two
            score: 10
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVerifyMultiResponse'
      type: object
      xml:
        name: RespVoiceprintVerifyMultiResponse
    RespVoiceprintVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 0.5
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVerifyResponse'
      type: object
      xml:
        name: RespVoiceprintVerifyResponse
    RespVoiceprinttopnVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          scores:
          - unionID: "123"
            score: 0.5
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprinttopnVerifyResponse'
      type: object
      xml:
        name: RespVoiceprinttopnVerifyResponse
    UnionIDScore:
      properties:
        unionID:
          description: union ID
          example: "123"
          type: string
        score:
          description: 得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: UnionIDScore
    UploadResponse:
      example:
        key: "123"
      properties:
        key:
          description: 文件key
          example: "123"
          type: string
      type: object
      xml:
        name: UploadResponse
    Voiceprint1tonVerifyRequest:
      example:
        appName: welab
        samplingRate: samplingRate
        unionIDs:
        - union_id2
        - union_id2
        url: "123456"
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionIDs:
          description: union IDs
          example:
          - union_id2
          - union_id2
          items:
            example: union_id2
            type: string
          type: array
        url:
          description: 文件url
          example: "123456"
          type: string
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionIDs
      - url
      type: object
      xml:
        name: Voiceprint1tonVerifyRequest
    Voiceprint1tonVerifyResponse:
      example:
        score: 0.5
        unionID: "123"
      properties:
        unionID:
          description: union ID
          example: "123"
          type: string
        score:
          description: 得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: Voiceprint1tonVerifyResponse
    VoiceprintCtcdasrRequest:
      example:
        duration: 0
        appName: appName
        samplingRate: samplingRate
        url: storage/xxxx-xxxx
        timestamp: 0
      properties:
        appName:
          description: 应用名字
          type: string
        url:
          description: 文件url
          example: storage/xxxx-xxxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 0
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintCtcdasrRequest
    VoiceprintCtcdasrResponse:
      example:
        asrString: "123456"
      properties:
        asrString:
          description: 数字asr
          example: "123456"
          type: string
      type: object
      xml:
        name: VoiceprintCtcdasrResponse
    VoiceprintDeleteRequest:
      example:
        unionID: unionID
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        unionID:
          description: union ID
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintDeleteRequest
    VoiceprintDeleteResponse:
      xml:
        name: VoiceprintDeleteResponse
    VoiceprintQueryRequest:
      example:
        unionID: unionID
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        unionID:
          description: union ID
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintQueryRequest
    VoiceprintQueryResponse:
      example:
        isRegister: true
      properties:
        isRegister:
          description: 是否注册
          type: boolean
      type: object
      xml:
        name: VoiceprintQueryResponse
    VoiceprintRegisterRequest:
      example:
        urls:
        - "123"
        - "45"
        - "666"
        unionID: unionID
        appName: appName
        replace: true
        samplingRate: 8k
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        replace:
          description: 是否替换
          type: boolean
        unionID:
          description: union ID
          type: string
        urls:
          description: 文件url数组
          example:
          - "123"
          - "45"
          - "666"
          items:
            example: "123"
            type: string
          type: array
        samplingRate:
          description: sampling rate
          example: 8k
          type: string
        timestamp:
          description: 时间戳
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintRegisterRequest
    VoiceprintRegisterResponse:
      xml:
        name: VoiceprintRegisterResponse
    VoiceprintThresholdRequest:
      example:
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      type: object
      xml:
        name: VoiceprintThresholdRequest
    VoiceprintThresholdResponse:
      example:
        threshold: 0.38
      properties:
        threshold:
          description: 阈值
          example: 0.38
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintThresholdResponse
    VoiceprintVadcheckRequest:
      example:
        duration: 0
        appName: appName
        samplingRate: samplingRate
        url: url
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        url:
          description: 文件url
          type: string
        samplingRate:
          description: sampling rate
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintVadcheckRequest
    VoiceprintVadcheckResponse:
      example:
        code: code
        status: status
      properties:
        code:
          description: vad check code
          type: string
        status:
          description: vad check status
          type: string
      type: object
      xml:
        name: VoiceprintVadcheckResponse
    VoiceprintVerifyMultiReport:
      properties:
        unionID:
          description: 唯一id
          example: use_one
          type: string
        score:
          description: 分数
          example: 99
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintVerifyMultiReport
    VoiceprintVerifyMultiRequest:
      example:
        urls:
        - "123456"
        - "1234567"
        appName: welab
        samplingRate: samplingRate
        unionIDs:
        - use_one
        - use_two
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionIDs:
          description: 唯一ID
          example:
          - use_one
          - use_two
          items:
            example: use_one
            type: string
          type: array
        urls:
          description: 文件url
          example:
          - "123456"
          - "1234567"
          items:
            example: "123456"
            type: string
          type: array
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionIDs
      - urls
      type: object
      xml:
        name: VoiceprintVerifyMultiRequest
    VoiceprintVerifyMultiResponse:
      example:
        report:
        - unionID: use_one
          score: 99
        - unionID: use_two
          score: 10
      properties:
        report:
          description: 结果
          example:
          - unionID: use_one
            score: 99
          - unionID: use_two
            score: 10
          items:
            $ref: '#/components/schemas/VoiceprintVerifyMultiReport'
          type: array
      type: object
      xml:
        name: VoiceprintVerifyMultiResponse
    VoiceprintVerifyRequest:
      example:
        unionID: use_one
        appName: welab
        samplingRate: samplingRate
        url: "123456"
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionID:
          description: 唯一ID
          example: use_one
          type: string
        url:
          description: 文件url
          example: "123456"
          type: string
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionID
      - url
      type: object
      xml:
        name: VoiceprintVerifyRequest
    VoiceprintVerifyResponse:
      example:
        score: 0.5
      properties:
        score:
          description: 声纹得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintVerifyResponse
    VoiceprinttopnVerifyRequest:
      example:
        urls: []
        appName: test
        samplingRate: samplingRate
        topn: 10
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: test
          type: string
        urls:
          description: 文件url
          example: []
          items:
            type: string
          type: array
        samplingRate:
          description: sampling rate
          type: string
        topn:
          description: top n
          example: 10
          format: int64
          type: integer
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - topn
      - urls
      type: object
      xml:
        name: VoiceprinttopnVerifyRequest
    VoiceprinttopnVerifyResponse:
      example:
        scores:
        - unionID: "123"
          score: 0.5
      properties:
        scores:
          description: topn排序
          example:
          - unionID: "123"
            score: 0.5
          items:
            $ref: '#/components/schemas/UnionIDScore'
          type: array
      type: object
      xml:
        name: VoiceprinttopnVerifyResponse
    body:
      properties:
        file:
          format: binary
          type: string
